version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Chạy quyền root để Jenkins điều khiển được Docker máy chủ
    ports:
      - "8081:8080"   # Cổng web Jenkins
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Cho phép Jenkins dùng Docker thật
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9001:9000"   # Cổng web SonarQube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  jenkins_home: